### ISSUE TITLE
Script to validate urls

### ISSUE THREAD

**Issue by reuteras** [cstromblad/cybersecurity_sources#4]
Hi!

While looking at the feeds before adding them to my rss reader I found some redirects and errors. Many are from companies being bought or no longer existing. 

I wrote this little **bash** script to check the status code returned from the feed in the list (no check of the redirected url for 3xx). The script requires that **curl** and **trurl** are available. 

Run it as `bash test_rss.sh | sort -k 2,2 | uniq > new.md` where a sorted new list will be in _new.md_ and status for every feed will be output to stderr during execution of the script.

```bash
#!/bin/bash

for line in $(curl -s https://raw.githubusercontent.com/cstromblad/cybersecurity_sources/refs/heads/main/sources.md | cut -f2 -d\ ); do
    url=$(echo "$line" | cut -f2 -d\ )
    status_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
    if [[ ${status_code} =~ 2.* ]]; then
        >&2 echo "200: $url"
        echo "- $url"
        continue
    fi
    if [[ ${status_code} =~ 3.* ]]; then
        location=$(curl -s -o /dev/null -w "%{header_json}" "$url")
        if [[ "$location" =~ .*location.* ]]; then
            redirect=$(echo "$location" | jq '.location[]' | tr -d '"' )
        else
            >&2 echo "Error: No location header for $url with status code ${status_code}"
        fi
        if [[ $redirect =~ http.* ]]; then
            new_url=$redirect
        else
            base=$(trurl --get "{scheme}://{host}" "$url")
            new_url=$base$redirect
        fi
        >&2 echo "3xx $url redirects to: ${new_url}"
        echo "- ${new_url}"
        continue
    fi
    >&2 echo "Error code ${status_code} returned for: $url"
done
```

I should have written it in python from the beginning... :)

**Comment by cstromblad** [comment]
Oh, good stuff. Will do that and prune dead feeds, appreciate the contribution :-D

**Comment by cstromblad** [comment]
Ran the script, was missing trurl, rerunning now and once complete I will replace the file with an updated version!

**Comment by cstromblad** [comment]
Updated! :-)
